# Generated by Django 4.2.5 on 2023-09-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя товара')),
                ('description', models.TextField(verbose_name='Описание товара')),
                ('price', models.IntegerField(verbose_name='Цена товара')),
                ('availability', models.BooleanField(default=True, verbose_name='В наличии')),
                ('group', models.CharField(choices=[('mobeli', 'mobile'), ('accessories', 'accessories'), ('pc', 'personalComputer'), ('notebook', 'notebook')], default='mobeli', max_length=20)),
                ('img', models.ImageField(default='noimage.jpg', upload_to='product_image')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
