# Generated by Django 4.2.5 on 2023-09-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_delete_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('pc', 'personalComputer'), ('accessories', 'accessories'), ('mobeli', 'mobile'), ('notebook', 'notebook')], default='mobeli', max_length=20, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default='noimage.jpg', upload_to='product_image', verbose_name='Картинка'),
        ),
    ]
