# Generated by Django 4.2.5 on 2023-09-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_group_alter_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('accessories', 'accessories'), ('mobile', 'mobile'), ('notebook', 'notebook'), ('pc', 'personalComputer')], default='mobile', max_length=20, verbose_name='Группа'),
        ),
    ]
