# Generated by Django 4.2.5 on 2023-09-21 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('notebook', 'notebook'), ('mobile', 'mobile'), ('pc', 'personalComputer'), ('accessories', 'accessories')], default='mobile', max_length=20, verbose_name='Группа'),
        ),
    ]
